version: '3'
services:
  nik-checker:
    build: .
    ports:
      - "5500:5500"
    env_file:
      - .env
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - mynetwork

networks:
  mynetwork:
